import { Router } from "express";
import { authenticate, optionalAuth } from "../middleware/auth.js";
import { requireRole } from "../middleware/require-role.js";
import * as auth from "../controllers/auth.controller.js";
import { authRateLimit } from "../middleware/auth-rate-limit.js";
import { handler as events } from "../controllers/events.controller.js";
import { handler as shows } from "../controllers/shows.controller.js";
import { handler as bookings } from "../controllers/bookings.controller.js";
import { adminRouter } from "./admin.routes.js";
export const apiRouter = Router();
apiRouter.post("/auth/register", authRateLimit, auth.register);
apiRouter.post("/auth/login", authRateLimit, auth.login);
apiRouter.get("/auth/me", authenticate, auth.me);
apiRouter.get("/me", authenticate, auth.me);
apiRouter.get("/events", events);
apiRouter.get("/events/:id", events);
apiRouter.get("/events/:id/shows", shows);
apiRouter.get("/shows/:id", shows);
apiRouter.get("/shows/:id/seats", optionalAuth, shows);
apiRouter.post("/shows/:id/seats/:seat_id/hold", authenticate, shows);
apiRouter.post("/shows/:id/holds", authenticate, shows);
apiRouter.get("/shows/:id/holds/:hold_token", authenticate, shows);
apiRouter.delete("/shows/:id/holds/:hold_token", authenticate, shows);
apiRouter.post("/bookings/confirm", authenticate, bookings);
apiRouter.get("/bookings", authenticate, bookings);
apiRouter.get("/bookings/:id", authenticate, bookings);
apiRouter.use("/admin", authenticate, requireRole("admin"), adminRouter);
